# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2015. #zanata
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2017. #zanata
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-10-15 09:53+0200\n"
"PO-Revision-Date: 2018-05-18 09:06+0000\n"
"Last-Translator: Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>\n"
"Language-Team: Catalan\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ca\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 4.6.2\n"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:40
msgid "the color of the sky"
msgstr "el color del cel"

#: ../plugins/system_upgrade.py:56
msgid "Need a --releasever greater than the current system version."
msgstr "Necessita un--releasever més gran que la versió del sistema actual."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:58
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""
"S'ha completat la baixada! Utilitzeu «dnf system-upgrade reboot» per començar l'actualització de versió.\n"
"Per suprimir les metadades capturades i la transacció utilitzeu «dnf system-upgrade clean»."

#: ../plugins/system_upgrade.py:61
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""
"Ho sentim, heu d'utilitzar «download --releasever» en lloc de «--network»"

#: ../plugins/system_upgrade.py:236
msgid "The following boots appear to contain upgrade logs:"
msgstr ""
"Les següents arrencades semblen que continguin registres d'actualització de "
"versió:"

#: ../plugins/system_upgrade.py:246
msgid "-- no logs were found --"
msgstr "-- no s'ha trobat cap registre --"

#: ../plugins/system_upgrade.py:261
msgid "Cannot find logs with this index."
msgstr "No s'ha pogut trobar cap registre amb aquest índex."

#: ../plugins/system_upgrade.py:270
msgid "Unable to match systemd journal entry"
msgstr ""

#: ../plugins/system_upgrade.py:289
msgid "Prepare system for upgrade to a new release"
msgstr ""
"Prepara el sistema per a una actualització de versió a un nou llançament"

#: ../plugins/system_upgrade.py:299
msgid "keep installed packages if the new release's version is older"
msgstr ""
"mantén els paquets instal·lats si la versió del nou llançament és més antiga"

#: ../plugins/system_upgrade.py:303
msgid "which logs to show"
msgstr "quins registres s'han de mostrar"

#: ../plugins/system_upgrade.py:359
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"Abans de continuar, assegureu-vos que el vostre sistema estigui completament"
" actualitzat amb l'execució de «dnf --refresh upgrade». Voleu continuar"

#: ../plugins/system_upgrade.py:363
msgid "Operation aborted."
msgstr "S'ha avortat l'operació."

#: ../plugins/system_upgrade.py:416
msgid "system is not ready for upgrade"
msgstr "el sistema no està preparat per una actualització de versió"

#: ../plugins/system_upgrade.py:418
msgid "upgrade is already scheduled"
msgstr "l'actualització de versió ja està programada"

#: ../plugins/system_upgrade.py:424
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:427
msgid "another upgrade tool is running. exiting quietly."
msgstr ""
"una altra eina d'actualització de versió està en execució. Se surt "
"ràpidament."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:433
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""
"utilitzeu «dnf system-upgrade reboot» per començar l'actualització de versió"

#: ../plugins/system_upgrade.py:450
msgid "Rebooting to perform upgrade."
msgstr "Es reinicia per a realitzar l'actualització de versió."

#: ../plugins/system_upgrade.py:472 ../plugins/system_upgrade.py:478
msgid "Starting system upgrade. This will take a while."
msgstr "S'inicia l'actualització de versió. Això pot trigar una estona."

#: ../plugins/system_upgrade.py:504
#, python-format
msgid "Unable to match package: %s"
msgstr ""

#: ../plugins/system_upgrade.py:509
msgid "Unable to match some of packages"
msgstr ""

#: ../plugins/system_upgrade.py:512
msgid "Cleaning up downloaded data..."
msgstr "Neteja de les dades baixades..."

#: ../plugins/system_upgrade.py:550
msgid "Download finished."
msgstr "S'ha finalitzat la baixada."

#: ../plugins/system_upgrade.py:554 ../plugins/system_upgrade.py:555
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr ""
"S'ha completat l'actualització de la versió. Es neteja i es reinicia..."

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr "Per a més informació executeu:"

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr "La crida a l'API del traçador ha acabat de forma inesperada:"

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Visiteu https://github.com/FrostyX/tracer/issues i envieu la incidència. "
"Moltes gràcies"

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "Us demanem disculpes per qualsevol inconvenient"

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "S'afegeix '{}' a la llista dels paquets tractats pel rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "ara s'executarà el connector rpmconf en mode no interactiu"

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "s'ignora sys.exit del rpmconf a causa que falta la variable MERGE"

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "s'ignora sys.exit del rpmconf a causa que falta un fitxer"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "la connexió amb el snapperd ha fallat: %s"

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: ../plugins/snapper.py:71
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: ../plugins/snapper.py:77
msgid "creating post_snapshot"
msgstr ""

#: ../plugins/snapper.py:82
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:86
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""

#: ../plugins/kickstart.py:59
msgid "Install packages defined in a kickstart file on your system"
msgstr ""
"Instal·la al vostre sistema els paquets definits en un fitxer kickstart"

#: ../plugins/kickstart.py:64
msgid "kickstart file"
msgstr "fitxer kickstart"

#: ../plugins/kickstart.py:82
#, python-format
msgid "file cannot be parsed: %s"
msgstr "no es pot analitzar sintàcticament el fitxer: %s"

#: ../plugins/kickstart.py:99
#, python-format
msgid "No package %s available."
msgstr "No hi ha cap paquet %s disponible."

#: ../plugins/kickstart.py:104
msgid "Nothing to do."
msgstr "No s'ha de fer res."

#: ../plugins/torproxy.py:32
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
"Inhabilitació del connector torproxy: no es pot connectar a la xarxa Tor"
