# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2015. #zanata
# Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-12-03 13:34+0100\n"
"PO-Revision-Date: 2016-10-22 04:08-0400\n"
"Last-Translator: Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>\n"
"Language-Team: Catalan\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ca\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/repoclosure.py:46
msgid "Display a list of unresolved dependencies for repositories"
msgstr "Mostra un llistat de les dependències sense resoldre per als dipòsits"

#: ../plugins/repoclosure.py:117
msgid "check packages of the given archs, can be specified multiple times"
msgstr ""

#: ../plugins/repoclosure.py:120
msgid "Specify repositories to check"
msgstr "Especifica els dipòsits a comprovar"

#: ../plugins/repoclosure.py:122
msgid "Check only the newest packages in the repos"
msgstr ""

#: ../plugins/repoclosure.py:125
msgid "Check closure for this package only"
msgstr "Comprova la conclusió per tan sols aquest paquet"

#: ../plugins/versionlock.py:32
#, python-format
msgid "Unable to read version lock configuration: %s"
msgstr "No es pot llegir la configuració del bloqueig de versió: %s"

#: ../plugins/versionlock.py:33
msgid "Locklist not set"
msgstr "Llista de bloqueig sense establir"

#: ../plugins/versionlock.py:34
msgid "Adding versionlock on:"
msgstr "S'afegeix el bloqueig de versió:"

#: ../plugins/versionlock.py:35
msgid "Adding exclude on:"
msgstr "S'afegeix l'exclusió:"

#: ../plugins/versionlock.py:36
msgid "Deleting versionlock for:"
msgstr "S'elimina el bloqueig de versió per:"

#: ../plugins/versionlock.py:37
msgid "No package found for:"
msgstr "No s'ha trobat el paquet de:"

#: ../plugins/versionlock.py:89
msgid "control package version locks"
msgstr "control del bloqueig de versió del paquet"

#: ../plugins/migrate.py:57
#, python-format
msgid "failed to parse package NEVRA from: %s"
msgstr "ha fallat l'anàlisi sintàctica NEVRA del paquet: %s"

#: ../plugins/migrate.py:78
msgid "migrate yum's history, group and yumdb data to dnf"
msgstr "migra l'històric, els grups, i les dades de la yumdb, del yum al dnf"

#: ../plugins/migrate.py:95
msgid "which kind of yum data migrate."
msgstr "el tipus de dades del yum que han de migrar-se."

#: ../plugins/migrate.py:111
msgid "Migrating history data..."
msgstr "Es migren les dades de l'històric..."

#: ../plugins/migrate.py:222
msgid "Migrating groups data..."
msgstr "Es migren les dades dels grups..."

#: ../plugins/migrate.py:227
msgid "Execution of Yum failed. Could not retrieve installed groups."
msgstr ""
"Ha fallat l'execució de Yum. No s'han pogut recuperar els grups instal·lats."

#: ../plugins/migrate.py:231
msgid "No groups to migrate from Yum"
msgstr "No hi ha grups a migrar del Yum"

#: ../plugins/migrate.py:243
msgid "skipping."
msgstr "s'ignora."

#: ../plugins/migrate.py:263
msgid "Migrating YUMDB data..."
msgstr "Es migren les dades de la YUMDB..."

#: ../plugins/migrate.py:282
#, python-format
msgid "%s of %s not found"
msgstr "%s de %s no trobats"

#: ../plugins/migrate.py:289
#, python-format
msgid "replacing unknown characters in %s of %s"
msgstr "s'estan substituint els caràcters desconeguts en %s de %s"

#: ../plugins/migrate.py:294
msgid "DNFDB access denied"
msgstr "S'ha denegat l'accés a la DNFDB"

#: ../plugins/migrate.py:296
#, python-format
msgid "%s of %s migrated"
msgstr "%s de %s migrats"

#: ../plugins/migrate.py:300
#, python-format
msgid "%d YUMDB records found, %d migrated, %d skipped/preserved"
msgstr "%d registres trobats de la YUMDB, %d migrats, %d ignorats/preservats"

#: ../plugins/repograph.py:54
msgid "Output a full package dependency graph in dot format"
msgstr ""
"Sortida d'un gràfic de totes les dependències del paquet en format dot"

#: ../plugins/repograph.py:115
#, python-format
msgid "Nothing provides: '%s'"
msgstr "No hi ha res que proporcioni: '%s'"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr ""
"Instal·la al vostre sistema els paquets definits en un fitxer kickstart"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr ""

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "no es pot analitzar sintàcticament el fitxer: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "No hi ha cap paquet %s disponible."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "No s'ha de fer res."

#: ../plugins/show_leaves.py:56
msgid "New leaves:"
msgstr "Nous abandonaments:"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "la connexió amb el snapperd ha fallat: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "es crea la instantània"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "s'ha creat la instantània %d"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr "la creació de la instantània ha fallat: %s"

#: ../plugins/repomanage.py:44
msgid "Manage a directory of rpm packages"
msgstr "Gestiona un directori de paquets rpm"

#: ../plugins/repomanage.py:52
msgid "Pass either --old or --new, not both!"
msgstr "Passeu --old o --new, però no ambdós!"

#: ../plugins/repomanage.py:62
msgid "No files to process"
msgstr "Sense fitxers per processar"

#: ../plugins/repomanage.py:67
msgid "Could not open {}"
msgstr "No es pot obrir {}"

#: ../plugins/repomanage.py:124
msgid "Print the older packages"
msgstr "Imprimeix els paquets més antics"

#: ../plugins/repomanage.py:126
msgid "Print the newest packages"
msgstr "Imprimeix els paquets més nous"

#: ../plugins/repomanage.py:128
msgid "Space separated output, not newline"
msgstr "Sortida separada amb espais, no línies noves"

#: ../plugins/repomanage.py:130
msgid "Newest N packages to keep - defaults to 1"
msgstr "Els N paquets més recents a conservar - per defecte 1"

#: ../plugins/repomanage.py:133
msgid "Path to directory"
msgstr "Camí al directori"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "S'afegeix '{}' a la llista dels paquets tractats pel rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/leaves.py:32
msgid "List installed packages not required by any other package"
msgstr ""
"Llista els paquets instal·lats que no es requereixin per cap altre paquet"

#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr ""

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr ""

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr ""

#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr ""

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr ""

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr ""

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr ""

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr ""

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr ""

#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr ""

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr ""

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr ""

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr ""

#: ../plugins/debug.py:55
msgid "dump information about installed rpm packages to file"
msgstr "bolca al fitxer la informació quant als paquets rpm instal·lats"

#: ../plugins/debug.py:69
msgid "do not attempt to dump the repository contents."
msgstr "no provis de bolcar el contingut dels dipòsits."

#: ../plugins/debug.py:72
msgid "optional name of dump file"
msgstr "nom opcional del fitxer del blocat"

#: ../plugins/debug.py:97
#, python-format
msgid "Output written to: %s"
msgstr "La sortida es va escriure a: %s"

#: ../plugins/debug.py:175
msgid "restore packages recorded in debug-dump file"
msgstr "restaura els paquets registrats al fitxer de depuració de bolcat"

#: ../plugins/debug.py:186
msgid "output commands that would be run to stdout."
msgstr "imprimeix les ordres que s'executen per la sortida estàndard."

#: ../plugins/debug.py:189
msgid "Install the latest version of recorded packages."
msgstr "Instal·la la darrera versió dels paquets registrats."

#: ../plugins/debug.py:192
msgid ""
"Ignore architecture and install missing packages matching the name, epoch, "
"version and release."
msgstr ""

#: ../plugins/debug.py:197
msgid "limit to specified type"
msgstr "limita-ho al tipus especificat"

#: ../plugins/debug.py:199
msgid "name of dump file"
msgstr "nom del fitxer del blocat"

#: ../plugins/debug.py:268
#, python-format
msgid "Package %s is not available"
msgstr "El paquet %s no està disponible"

#: ../plugins/debug.py:278
#, python-format
msgid "Bad dnf debug file: %s"
msgstr "Fitxer incorrecte de depuració dnf: %s"

#: ../plugins/local.py:115
msgid "'{}' is not a directory"
msgstr "'{}' no és un directori"

#: ../plugins/local.py:124
msgid "Copying '{}' to local repo"
msgstr "Es copia '{}' al dipòsit local"

#: ../plugins/local.py:130
msgid "Can't write file '{}'"
msgstr "No es pot escriure el fitxer '{}'"

#: ../plugins/local.py:145
msgid "Rebuilding local repo"
msgstr "Es reconstrueix el dipòsit local"

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Per a més informació executeu:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Us demanem disculpes per qualsevol inconvenient"
