# Zdenek <chmelarz@gmail.com>, 2016. #zanata
# Zdenek <chmelarz@gmail.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-04-28 12:46+0200\n"
"PO-Revision-Date: 2017-02-14 07:59-0500\n"
"Last-Translator: Zdenek <chmelarz@gmail.com>\n"
"Language-Team: Czech\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: cs\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr "Instalovat balíčky definované v souboru kickstartu vašeho systému"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr "soubor kickstart"

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "soubor nelze parsovat: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "Balíček %s není k dispozici."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Není co dělat"

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Přidání '{}' do seznamu balíčků ovládání pro rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "zásuvný modul rpmconf nebude v neinteraktivním režimu spuštěn"

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "ignorování sys.exit z rpmconf kvůli chybějící proměnné MERGE"

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "ignorování sys.exit z rpmconf kvůli chybějícímu souboru"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "selhalo připojení ke Snapperu: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "vytváření obrazu"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "obraz %d vytvořen"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr "selhalo vytvoření obrazu: %s"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr "barva oblohy"

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr "Nenalezeny nové balíčky jádra."

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr "Verze --releasever musí být vyšší než verze aktuálního systému."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""
"Stahování dokončeno! Aktualizaci spustíte příkazem 'dnf system-upgrade "
"reboot'."

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Promiňte, místo '--network' musíte použít 'download --releasever'"

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr "--datadir: Soubor už existuje"

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr "Následující boot obsahuje záznamy aktualizace systému:"

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr "-- nenalezeny žádné záznamy --"

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr "Nenalezeny žádné záznamy s tímto indexem."

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr "Připravit systém k aktualizaci na novou verzi"

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr "uložit stažená data na toto místo"

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""
"ponechat nainstalované balíčky, pokud se v novém vydání nachází starší verze"

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr "systém není na aktualizaci připraven"

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr "aktualizace je už naplánována"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "pro zahájení aktualizace zadejte 'dnf system-upgrade reboot'"

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr "už běží jiný aktualizační nástroj, končím."

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr "Restartuji, aby se provedla aktualizace."

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr "Spouští se aktualizace systému. To může nějakou dobu trvat."

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr "Mazání stažených dat…"

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr "Stahování dokončeno."

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Aktualizace dokončena! Čištění a restart systému…"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "Zakázání zásuvného modulu torproxy: nelze se připojit do sítě Tor"

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Pro více informací spustit:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr "Volání Tracer API neočekávaně skončilo"

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Navštivte prosím https://github.com/FrostyX/tracer/issues a nahlašte "
"problém. Děkuji"

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Omlouváme se za způsobené nepříjemnosti"
