# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Piotr Drąg <piotrdrag@gmail.com>, 2015
# Piotr Drąg <piotrdrag@gmail.com>, 2015. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2016. #zanata
# Piotr Drąg <piotrdrag@gmail.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-04-07 14:44+0200\n"
"PO-Revision-Date: 2017-03-27 08:01-0400\n"
"Last-Translator: Piotr Drąg <piotrdrag@gmail.com>\n"
"Language-Team: Polish (http://www.transifex.com/projects/p/dnf-plugins-extras/language/pl/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pl\n"
"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr "Instaluje pakiety podane w pliku kickstart w systemie"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr "plik kickstart"

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "nie można przetworzyć pliku: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "Pakiet %s jest niedostępny."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Nie ma nic do zrobienia."

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "Dodawanie „{}” do listy obsługiwanych pakietów dla rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "Wtyczka rpmconf nie będzie działała w trybie nieinteraktywnym"

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "ignorowanie sys.exit z rpmconf z powodu braku zmiennej „MERGE”"

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "ignorowanie sys.exit z rpmconf z powodu braku pliku"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "połączenie z snapperd się nie powiodło: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "tworzenie migawki"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "utworzono migawkę %d"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr "utworzenie migawki się nie powiodło: %s"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr "kolor nieba"

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr "Nie odnaleziono żadnych nowych pakietów jądra."

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr ""
"Parametr „--releasever” wymaga wartości wyższej niż wersja obecnego systemu."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""
"Ukończono pobieranie. Polecenie „dnf system-upgrade reboot” rozpocznie "
"aktualizację systemu."

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr "Należy użyć opcji „download --releasever” zamiast „--network”"

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr "--datadir: plik istnieje"

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr "Następujące uruchomienia zawierają dzienniki aktualizacji:"

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr "-- nie odnaleziono dzienników --"

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr "Nie można odnaleźć dzienników za pomocą tego indeksu."

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr "Przygotowuje system do aktualizacji do nowego wydania"

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr "zapisuje pobrane dane w tym położeniu"

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""
"zachowuje zainstalowane pakiety, jeśli wersja nowego wydania jest starsza"

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr "system nie jest gotowy na aktualizację"

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr "aktualizacja jest już zaplanowana"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "polecenie „dnf system-upgrade reboot” rozpocznie aktualizację systemu"

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr ""
"inne narzędzie do aktualizacji systemu jest uruchomione. Ciche kończenie "
"działania."

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr "Ponowne uruchamianie, aby wykonać aktualizację."

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr "Rozpoczynanie aktualizacji systemu. Może to chwilę zająć."

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr "Czyszczenie pobranych danych…"

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr "Ukończono pobieranie."

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Ukończono aktualizację systemu. Czyszczenie i ponowne uruchamianie…"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "Wyłączanie wtyczki torproxy: nie można połączyć z siecią Tor"

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Więcej informacji:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr "Wywołanie do API Tracer nieoczekiwanie zakończyło działanie:"

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Proszę zgłosić błąd na stronie https://github.com/FrostyX/tracer/issues (w "
"języku angielskim)"

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Przepraszamy za niedogodności"
