# Daniel Lara <danniel@fedoraproject.org>, 2016. #zanata
# Marco Aurélio Krause <ouesten@me.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-04-07 14:44+0200\n"
"PO-Revision-Date: 2016-11-26 09:46-0500\n"
"Last-Translator: Marco Aurélio Krause <ouesten@me.com>\n"
"Language-Team: Portuguese (Brazil)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt-BR\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr ""
"Instalar em seu sistema os pacotes definidos em um arquivo do kickstart"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr "arquivo kickstart"

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "arquivo não pode ser analisado: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "Nenhum pacote %s disponível."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Nada a ser feito."

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr ""
"Adicionando '{}' para a lista de pacotes de manipulação para o rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "O plugin rpmconf não será executado em modo não interativo"

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "conexão com o snapperd falhou: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "criando snapshot"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "snapshot criado %d"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr "falha ao criar snapshot: %s"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr "a cor do céu"

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr "Nenhum pacote novo do kernel foi encontrado."

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr "Necessita de um --releasever maior que o da versão do sistema atual."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""
"Desculpe, você precisa utilizar 'download --releasever' ao invés de '--"
"network'"

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr "--datadir: Existem arquivos"

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr "As seguintes inicializações parecem conter registros de atualizações:"

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr "-- nenhum registro encontrado --"

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr "Não foi possível encontrar registros com este índice."

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr "Preparar o sistema para atualizar para uma nova versão"

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr "salvando dados descarregados para essa localização"

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr "manter os pacotes instalados se os da nova versão forem mais antigos"

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr "o sistema não está pronto para uma atualização"

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr "a atualização já está agendada"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr "outra ferramenta de atualização em execução. saindo silenciosamente."

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr "Reiniciando para realizar a atualização."

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr "Iniciando a atualização do sistema. Isso vai levar algum tempo."

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr "Limpando os dados descarregados..."

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr "Download concluído."

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Atualização completa! Limpando e reiniciando..."

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr "Desativando o plugin torproxy: não poderá se conectar à rede Tor"

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Para mais informações execute:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Visite https://github.com/FrostyX/tracer/issues e envie o problema. Obrigado"

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Nos desculpamos por qualquer inconveniência"
